
export const appAccessControlList = {
  all: 'all',
  create_departments: 'create-departments',
  create_organisations: 'create-organisations',
  create_permissions: 'create-permissions',
  create_roles: 'create-roles',
  delete_departments: 'delete-departments',
  delete_organisations: 'delete-organisations',
  delete_permissions: 'delete-permissions',
  delete_roles: 'delete-roles',
  list_departments: 'list-departments',
  list_organisations: 'list-organisations',
  list_permissions: 'list-permissions',
  list_roles: 'list-roles',
  manage_departments: 'manage-departments',
  manage_organisations: 'manage-organisations',
  manage_permissions: 'manage-permissions',
  manage_roles: 'manage-roles',
  update_departments: 'update-departments',
  update_organisations: 'update-organisations',
  update_password: 'update-password',
  update_permissions: 'update-permissions',
  update_roles: 'update-roles',
  list_modules: 'list-modules',
  create_modules: 'create-modules',
  update_modules: 'update-modules',
  delete_modules: 'delete-modules'
};
