export const backendRoutes = {
  members: 'ressources/members',
  contributionNotificationEndpoint: 'ressources/rtiei_contribution_declaration_notification/',
  liquidationPath: 'ressources/liquidations',
  immRequestPath: 'ressources/imm_requests',
  rtieiSlipsPath: 'ressources/rtiei_slips',
  liquidationDecomptePath: 'ressources/decompte-liquidations',
  rtieiGenerateLocalSlipsPath: 'ressources/generate_local_rtiei_slips',
  rtieiGenerateFinancialSlipsPath: 'ressources/generate_financial_rtiei_slips',
  departmentPath: 'departments',
  inWorkersPath: 'ressources/members',
  structuresPath: 'ressources/structures',
  getMembershipRequestMemberDetails: 'ressources/rc_membership-member-details',
  contributionOptions: 'ressources/contribution_options',
  rcMemberships: 'ressources/rc_memberships',
  contributionDeclrationPath: 'ressources/rtiei_contribution_declarations',
  rcStructuresPath: 'ressources/rc_structures',
  rcMembersPath: 'ressources/rc_members',
  rcContributionDeclrationPath: 'ressources/rc_contribution_declarations',
};
