export const backendRoutes = {
  // Global modules routing defintions
  modules: 'ressources/modules',


  // Busness logic routing definitions
  members: 'ressources/rtiei-members',
  contributionNotificationEndpoint: 'ressources/rtiei-contribution-declaration-notification/',
  liquidationPath: 'ressources/rtiei-liquidations',
  immRequestPath: 'ressources/rtiei-membership-requests',
  rtieiSlipsPath: 'ressources/rtiei-slips',
  liquidationDecomptePath: 'ressources/decompte-liquidations',
  rtieiGenerateLocalSlipsPath: 'ressources/generate-local-rtiei-slips',
  rtieiGenerateFinancialSlipsPath: 'ressources/generate-financial-rtiei-slips',
  departmentPath: 'departments',
  inWorkersPath: 'ressources/rtiei-members',
  structuresPath: 'ressources/rtiei-structures',
  getMembershipRequestMemberDetails: 'ressources/rc-membership-member-details',
  contributionOptions: 'ressources/contribution-options',
  rcMemberships: 'ressources/rc-memberships',
  contributionDeclrationPath: 'ressources/rtiei-contribution-declarations',
  rcStructuresPath: 'ressources/rc-structures',
  rcMembersPath: 'ressources/rc-members',
  rcContributionDeclrationPath: 'ressources/rc-contribution-declarations',
  individualStatementPath: 'ressources/member-rtiei-contribution-account-statements',
  contributionStatementPath: 'ressources/rtiei-contribution-account-statements',
  rcIndividualStatementPath: 'ressources/member-rc-contribution-account-statements',
  rcContributionStatementPath: 'ressources/rc-contribution-account-statements',
  rtieiContributionPaymentsPath: 'ressources/rtiei-contribution-payments',
  rcContributionPaymentsPath: 'ressources/rc-contribution-declaration-payments',
  rcLiquidationPath: 'ressources/rc-liquidations',
  rcLiquidationDecomptePath: 'ressources/decompte-rc-liquidations',
  contributionAccountTransactionsPaths: 'ressources/account-transactions',
  rnMembersPath: 'ressources/rn-members',
  rnStructuresPath: 'ressources/rn-structures',
  rcMembershipMembersPath: 'ressources/rc-membership-members',
  rcMembershipFilePath: 'ressources/rc-membership/files',
  globalConfigurationsPath: 'ressources/application-configurations',
  regimesPath: 'ressources/regimes',
  branchesPath: 'ressources/branches',
  subBranchesPath: 'ressources/sub-branches',
  notificationTplsPath: 'ressources/notification-templates',
  notificationsPath: 'ressources/notifications',

  // Administration paths
  roles: 'roles',
  permissions: 'permissions',
  users: 'users',

  // Allowances and Annuitances routes
  rtieiAllowancesPath: 'ressources/rtiei-allowances',
  rtieiAnnuitancesPath: 'ressources/rtiei-annuitances',
  rtieiAllowancesPaymentSlipPath: 'ressources/rtiei-allowances-payment-slip',
  rtieiAnnuitancesPaymentSlipPath: 'ressources/rtiei-annuitances-payment-slip',
  rcAllowancesPath: 'ressources/rc-allowances',
  rcAnnuitancesPath: 'ressources/rc-annuitances',
};
